Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,47 +18,47 @@ strategy:
 
     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
-steps:
-  - uses: actions/checkout@v2
-    name: Use Node.js ${{ matrix.node-version }}
-    uses: actions/setup-node@v2
-    with:
-      node-version: ${{ matrix.node-version }}
-      cache: 'npm'
+  steps:
+    - uses: actions/checkout@v2
+      name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v2
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'npm'
 
-  - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
-    run: |
+    - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
+      run: |
 
-      VERSION=$(curl https://api.github.com/repos/snyk/cli/releases/latest | jq '.name' | tr -d '"')
-      wget https://github.com/snyk/cli/releases/download/$VERSION/snyk-linux.sha256
-      wget https://github.com/snyk/cli/releases/download/$VERSION/snyk-linux
+        VERSION=$(curl https://api.github.com/repos/snyk/cli/releases/latest | jq '.name' | tr -d '"')
+        wget https://github.com/snyk/cli/releases/download/$VERSION/snyk-linux.sha256
+        wget https://github.com/snyk/cli/releases/download/$VERSION/snyk-linux
 
-      SHA=$(sha256sum snyk-linux)
-      CHECK_SHA=$(cat snyk-linux.sha256)
+        SHA=$(sha256sum snyk-linux)
+        CHECK_SHA=$(cat snyk-linux.sha256)
 
-      if [[ $SHA == $CHECK_SHA ]]; then
-        echo "sha is good!"
-      else
-        echo "sha is not good :("
-      fi
+        if [[ $SHA == $CHECK_SHA ]]; then
+          echo "sha is good!"
+        else
+          echo "sha is not good :("
+        fi
 
-      npm install snyk -g
-      npm install snyk-to-html -g
-      snyk auth ${{secrets.SNYK_AUTH}}
+        npm install snyk -g
+        npm install snyk-to-html -g
+        snyk auth ${{secrets.SNYK_AUTH}}
 
-  - name: Snyk Open Source # For testing and failing please add snyk test or snyk test --all-projects before snyk monitor
-    run: |
-      snyk monitor
-      snyk test --all-projects
-# For a list of additional available flags/options see: https://docs.snyk.io/snyk-cli/commands
+    - name: Snyk Open Source # For testing and failing please add snyk test or snyk test --all-projects before snyk monitor
+      run: |
+        snyk monitor
+        snyk test --all-projects
+  # For a list of additional available flags/options see: https://docs.snyk.io/snyk-cli/commands
 
-  - name: Snyk Code # Remove || true to fail if there are vulnerabilities
-    run: |
-      snyk code test || true
-  - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
-    run: |
-      docker build . -t yourimage:tag
-      snyk container monitor yourimage:tag --file=Dockerfile
-  - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
-    run: |
-      snyk iac test || true
+    - name: Snyk Code # Remove || true to fail if there are vulnerabilities
+      run: |
+        snyk code test || true
+    - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
+      run: |
+        docker build . -t yourimage:tag
+        snyk container monitor yourimage:tag --file=Dockerfile
+    - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
+      run: |
+        snyk iac test || true
